# ===================================================================
# Specific properties [dev]
# ===================================================================

aws:
    role: arn:aws:iam
    session-name: example-session
