# ===================================================================
# Specific properties [prod]
# ===================================================================

aws:
    role: arn:aws:iam
    session-name: example-session